# Generated by Django 4.0.5 on 2022-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_faculties_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.TextField(db_index=True, max_length=30)),
                ('text', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
