# Generated by Django 4.0.5 on 2022-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
