# Generated by Django 4.0.5 on 2022-06-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_faculties_name_alter_groups_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuelParticipatingNow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstPeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('groupFirst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.groups')),
                ('groupSecond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.groups')),
                ('secondPeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Текущая пара оппонентов',
                'verbose_name_plural': 'Текущие пары оппонентов',
            },
        ),
        migrations.CreateModel(
            name='CommandParticipatingNow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('fifthPeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('firstPeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fourthPeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.groups')),
                ('secondPeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('thirdPeople', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Текущая команда мушкетеров',
                'verbose_name_plural': 'Текущие команды мушкетеров',
            },
        ),
    ]
