# Generated by Django 4.0.5 on 2022-06-17 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_commandparticipatingnow_fifthpeople_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandparticipatingnow',
            name='fifthPeople',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='commandparticipatingnow',
            name='fourthPeople',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LastWinners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True)),
                ('lineOne', models.CharField(db_index=True, max_length=30)),
                ('lineTwo', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('lineThree', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('lineFour', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('lineFive', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.groups', unique=True)),
            ],
            options={
                'verbose_name': 'Победители прошлого семестра',
                'verbose_name_plural': 'Победители прошлого семестра',
            },
        ),
    ]
