# Generated by Django 4.0.5 on 2022-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_commandparticipatingnow_fifthpeople_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandparticipatingnow',
            name='name',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название факультета'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(db_index=True, max_length=7, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineFive',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='участник №5 (для мушкетеров)'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineFour',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='участник №4 или уч.группа №2 (для мушкетеров или дуэлей)'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineOne',
            field=models.CharField(db_index=True, max_length=30, verbose_name='участник №1 или оппонент №1 (для мушкетеров или дуэлей)'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineThree',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='участник №3 или оппонент №2 (для мушкетеров или дуэлей)'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineTwo',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='участник №2 или уч.группа №1 (для мушкетеров или дуэлей)'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True, verbose_name='Название команды (для мушкетеров)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(db_index=True, max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Заголовок'),
        ),
    ]
