# Generated by Django 4.0.5 on 2022-06-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='duel',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Дуэли'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='groups',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Лучшие группы'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='musketeers',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Мушкетеры'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='semester',
            field=models.CharField(choices=[('Осн', 'Осенний'), ('Вес', 'Весенний')], db_index=True, max_length=8, verbose_name='Семестр'),
        ),
    ]
