# Generated by Django 4.0.5 on 2022-06-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_archive_duel_alter_archive_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name': 'Архив', 'verbose_name_plural': 'Архив'},
        ),
    ]
