# Generated by Django 4.0.5 on 2022-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_archive_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandparticipatingnow',
            name='fifthPeople',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True, verbose_name='Участник №5'),
        ),
        migrations.AlterField(
            model_name='commandparticipatingnow',
            name='firstPeople',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Участник №1'),
        ),
        migrations.AlterField(
            model_name='commandparticipatingnow',
            name='fourthPeople',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True, verbose_name='Участник №4'),
        ),
        migrations.AlterField(
            model_name='commandparticipatingnow',
            name='group',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Уч. группа'),
        ),
        migrations.AlterField(
            model_name='commandparticipatingnow',
            name='secondPeople',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Участник №2'),
        ),
        migrations.AlterField(
            model_name='commandparticipatingnow',
            name='thirdPeople',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Участник №3'),
        ),
        migrations.AlterField(
            model_name='duelparticipatingnow',
            name='firstPeople',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Участник №1'),
        ),
        migrations.AlterField(
            model_name='duelparticipatingnow',
            name='groupFirst',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Группа уч. №1'),
        ),
        migrations.AlterField(
            model_name='duelparticipatingnow',
            name='groupSecond',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Группа уч. №2'),
        ),
        migrations.AlterField(
            model_name='duelparticipatingnow',
            name='secondPeople',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Участник №2'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='group',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Уч. группа'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineFive',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='уч. №5 (для мушкетеров)'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineFour',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='уч. №4 или уч.группа №2 (для мушкетеров/дуэлей)'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineOne',
            field=models.CharField(db_index=True, max_length=30, verbose_name='уч. №1 или оппонент №1 (для мушкетеров/дуэлей)'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineThree',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='уч. №3 или оппонент №2 (для мушкетеров/дуэлей)'),
        ),
        migrations.AlterField(
            model_name='lastwinners',
            name='lineTwo',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='уч. №2 или уч.группа №1 (для мушкетеров/дуэлей)'),
        ),
    ]
