# Generated by Django 4.0.5 on 2022-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_lastwinners_group_alter_lastwinners_linefive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='semester',
            field=models.CharField(choices=[('Осенний', 'Осенний'), ('Весенний', 'Весенний')], db_index=True, max_length=8, verbose_name='Семестр'),
        ),
    ]
