# Generated by Django 4.0.5 on 2022-06-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_archive_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelparticipatingnow',
            name='acceptDuel',
            field=models.BooleanField(default=False, verbose_name='Дуэль подтв.'),
        ),
    ]
