# Generated by Django 4.0.5 on 2022-06-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_duelparticipatingnow_acceptduel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelparticipatingnow',
            name='groupFirst',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Группа уч. №1'),
        ),
        migrations.AlterField(
            model_name='duelparticipatingnow',
            name='groupSecond',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Группа уч. №2'),
        ),
    ]
