# Generated by Django 4.0.5 on 2022-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_commandparticipatingnow_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteDuelNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPeople', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Участник №1')),
                ('groupFirst', models.CharField(db_index=True, max_length=60, verbose_name='Группа уч. №1')),
                ('secondPeople', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Участник №2')),
                ('groupSecond', models.CharField(db_index=True, max_length=60, verbose_name='Группа уч. №2')),
                ('acceptDuel', models.BooleanField(default=False, verbose_name='Дуэль подтв.')),
            ],
            options={
                'verbose_name': 'Отправленные вызовы на дуэль',
                'verbose_name_plural': 'Отправленные вызовы на дуэль',
            },
        ),
        migrations.RemoveField(
            model_name='duelparticipatingnow',
            name='acceptDuel',
        ),
    ]
