# Generated by Django 4.0.5 on 2022-06-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_inviteduelnow_secondpeople'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteDuelNow',
        ),
        migrations.AddField(
            model_name='duelparticipatingnow',
            name='acceptDuel',
            field=models.BooleanField(default=False, verbose_name='Дуэль подтв.'),
        ),
    ]
