# Generated by Django 4.0.5 on 2022-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_delete_inviteduelnow_duelparticipatingnow_acceptduel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelparticipatingnow',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
