# Generated by Django 4.0.5 on 2022-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_duelparticipatingnow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelparticipatingnow',
            name='secondPeople',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Участник №2'),
        ),
    ]
